WebApplication1/Controllers/AccountViewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PostingManagement.UI.CustomActionFilters;
using PostingManagement.UI.Models;
using PostingManagement.UI.Models.AccountModels;
using PostingManagement.UI.Services.AccountServices.Contracts;
using PostingManagement.UI.Services.RoleService;

namespace PostingManagement.UI.Controllers
{
    [LoginFilter]
    public class AccountViewController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly IRoleService _roleService;
        public AccountViewController(IAccountService accountService, IRoleService roleService)
        {
            _accountService = accountService;
            _roleService = roleService;
        }

        [HttpGet]   
        public async Task<IActionResult> CreateUserName()
        {
            List<RoleModel> roles = await _roleService.GetAllRoles();
            //Dynamic ViewBag Contains the All Role Present.
            ViewBag.Roles = new SelectList(roles, "RoleId", "RoleName");
            if (TempData.ContainsKey("addUserResponse"))
            {
                ViewBag.CreateUserResponse = TempData["addUserResponse"].ToString();
            }
            return View();
        }

        [HttpPost]
        //Assigns The UserRole 
        public async Task<IActionResult> CreateUserName(CreateUserRequestModel model)
        {
            model.CreatedBy = HttpContext.Session.GetString("Username");
            var response = await _accountService.SaveUserDetails(model);
            //Storing response for Status Alert message
            if (response.Data != null)
            {
                TempData["addUserResponse"] = response.Data == true ? "true" : "false";
            }
            else
            {
                TempData["addUserResponse"] = "false";

            }
            return RedirectToAction("CreateUserName");
        }

        //Delete The UserRole By Using RoleId
        public async Task<IActionResult> DeleteUserName(string id)
        {
            var deletedBy = HttpContext.Session.GetString("Username");
            await _accountService.DeleteUserDetails(id, deletedBy);
            return RedirectToAction("CreateUserName");
        }

        [HttpGet]
        public async Task<IActionResult> EditUserRoleDetails(string id, string currentRole)
        {
            //Getting UserRole By Using RoleId 
            var model = await _accountService.GetUserById(id);

            List<RoleModel> roles = await _roleService.GetAllRoles();

            ViewBag.Roles = new SelectList(roles, "RoleId", "RoleName");
            ViewBag.UserCurrentRole = currentRole;
            return View(model.Data);
        }

        [HttpPost]
        //Edit UserRole By Using RoleId
        public async Task<IActionResult> EditUserRoleDetails(UserViewModel model)
        {
            UpdateUserRoleRequestModel request = new();
            request.UId = model.UId;
            request.UserName = model.UserName;
            request.RoleId = model.RoleId;
            request.Email = model.Email;
            request.UpdatedBy = HttpContext.Session.GetString("Username");

            await _accountService.UpdateUserDetails(request);
            return RedirectToAction("CreateUserName");
        }

        [HttpGet]
        //Show The All UserRole Present
        public async Task<IActionResult> ShowUserRoleDetails()
        {
            var userList = await _accountService.GetAllUserDetails();
            return Json(userList.Data);
        }

        [HttpGet]
        //Check the UserRole Is Present By Using User Name
        public async Task<IActionResult> IsUserNamePresent(string userName)
        {
            var response = await _accountService.IsUserNamePresent(userName);
            return Json(response.Data);
        }

    }
}

WebApplication1/Views/AccountView/CreateUserName.cshtml
@model PostingManagement.UI.Models.AccountModels.CreateUserRequestModel

@{
    ViewData["Title"] = "CreateUserName";
    Layout = "MainView";
}

<input type="hidden" value=@ViewBag.CreateUserResponse id="addUserResponse" />

<script src="~/js/createuserrole.js?v=1.2"></script>

<h1 class="card-title">Create New User</h1>

<hr />
<div class="col-xxl-4 col-xl-12">

    <div class="card info-card customers-card">

        <div class="card-body">

            <div class="row">
                <div class="col w-100">
                    <form asp-action="CreateUserName" id="CreateUserNameForm">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div style="display:inline-flex;" class="w-100">
                            <div class="form-group my-3 " style="width:20% ;margin-right:2%">
                                <label class="control-label">Roles<i class="text-danger">*</i> </label>
                                @if (ViewBag.Roles != null)
                                {
                                    @Html.DropDownListFor(model =>model.RoleId ,ViewBag.Roles as SelectList,"--select Roles--",new { @class="form-select me-3" })
                                }

                            </div>
                            <div class="form-group my-3">
                                <label class="control-label">User Name<i class="text-danger">*</i> </label>
                                <input asp-for="UserName" class="form-control" />
                            </div>
                            <div class="form-group m-3">
                                <label class="control-label">User Email<i class="text-danger">*</i> </label>
                                <input asp-for="Email" class="form-control" maxlength="50" />
                            </div>
                            <div class="form-group m-3 d-flex align-items-end ">
                                <input type="button" value="Save" id="CreateUserBtn" class="btn btn-success" />
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="card info-card customers-card">

        <div class="card-body">

            <h5 class="card-title"> All User Details <span></span></h5>
            <hr />
            <div>
                <partial name="_ShowUserRoleDetails">
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebApplication1/Views/AccountView/EditUserRoleDetails.cshtml
@model PostingManagement.UI.Models.AccountModels.UserViewModel

@{
    ViewData["Title"] = "EditUserRoleDetails";
    Layout = "MainView";
}

<script src="~/js/edituserrole.js?v=1.2"></script>
<h1 class="card-title">Edit User Role</h1>

<hr />
<div class="col-xxl-4 col-xl-12">
    <div class="card info-card customers-card">
        <div class="card-body">
            <div class="row">
                <div class="col w-100">
                    <form id="EditUserForm" asp-action="EditUserRoleDetails">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="w-100 d-flex justify-content-center">

                            <input asp-for="UId" class="form-control" type="hidden" />
                            <input asp-for="UserName" class="form-control" type="hidden" />

                            <div class="form-group m-3 w-25">
                                <label asp-for="UserName" class="control-label">User Name</label>
                                <input asp-for="UserName" class="form-control" disabled />
                            </div>
                            <div class="form-group m-3 w-25">
                                <label class="control-label">Old Role</label>
                                <input value="@ViewBag.UserCurrentRole" class="form-control" disabled />
                            </div>
                            </div>
                        <div class="w-100 d-flex justify-content-center">

                            <div class="form-group m-3 w-25">
                                <label asp-for="RoleId" class="control-label">New Role</label>
                                @if (ViewBag.Roles != null)
                                {
                                    @Html.DropDownListFor(model =>model.RoleId ,ViewBag.Roles as SelectList,new { @class="form-select" })
                                }
                                <span asp-validation-for="RoleId" class="text-danger"></span>
                            </div>
                            <div class="form-group m-3 w-25">
                                <label asp-for="Email" class="control-label">User Email</label>
                                <input asp-for="Email" class="form-control" maxlength="30"/>
                            </div>
                        </div>
                        <div class="w-100 d-flex justify-content-center">

                            <div class="form-group m-3 d-flex align-items-end w-25">
                                <input type="button" value="Save" id="EditUserBtn" class="btn btn-success my-4 w-100" />
                            </div>
                            <div class="form-group m-3 d-flex align-items-end w-25 ">
                                <a class="btn btn-primary my-4 w-100" asp-action="CreateUserName" asp-controller="AccountView">Back</a>
                            </div>

                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>

<div>
    <div class="card info-card customers-card">

        <div class="card-body">

            <h5 class="card-title"> All User Details <span></span></h5>
            <hr />
            <div>
                <partial name="_ShowUserRoleDetails">
            </div>
        </div>
    </div>
</div>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

WebApplication1/Views/AccountView/ShowUserRoleDetails.cshtml
@model IEnumerable<PostingManagement.UI.Models.AccountModels.UserViewModel>



<table id="userRoleDetails" class="display" style="width:100%">
    <thead>
        <tr>
            
            <th>Role</th>
            <th>User</th>
            <th></th>
           
        </tr>
    </thead>
    <tbody></tbody>
</table>

WebApplication1/Views/AccountView/_ShowUserRoleDetails.cshtml
<table id="userRoleDetails" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Role</th>
            <th>User</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>