WebApplication1/Controllers/PostingController.cs
using Microsoft.AspNetCore.Mvc;
using Nancy.Json;
using Newtonsoft.Json;
using PostingManagement.UI.CustomActionFilters;
using PostingManagement.UI.Helpers.Constants;
using PostingManagement.UI.Models;
using PostingManagement.UI.Models.ExcelFileTypes;
using PostingManagement.UI.Models.Responses;
using PostingManagement.UI.Services.ExcelUploadService.Contracts;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace PostingManagement.UI.Controllers
{
    [LoginFilter]
    public class PostingController : Controller
    {
        private readonly IHostingEnvironment _environment;
        private readonly IExcelUploadService _service;
        private readonly IHttpContextAccessor _httpContext;
        public PostingController(IExcelUploadService service, IHttpContextAccessor httpContext, IHostingEnvironment environment)
        {
            _environment = environment;
            _service = service;
            _httpContext = httpContext;
        }

        [HttpGet]
        //Employee Excel Upload Using FileType Code
        public async Task<IActionResult> EmployeeMasterUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.EmployeeMaster);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.EmployeeMaster));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //Branch Excel Upload Using FileType Code
        public async Task<IActionResult> BranchMasterUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.BranchMaster);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.BranchMaster));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //Department Excel Upload Using FileType Code
        public async Task<IActionResult> DepartmentMasterUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.DepartmentMaster);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.DepartmentMaster));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //zone Excel Upload Using FileType Code
        public async Task<IActionResult> ZoneMasterUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.ZoneMaster);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.ZoneMaster));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //Region Excel Upload Using FileType Code
        public async Task<IActionResult> RegionMasterUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.RegionMaster);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.RegionMaster));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //Department Excel Upload Using FileType Code
        public async Task<IActionResult> InterZonalRequestTransferUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.InterZonalRequestTranfer);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.InterZonalRequestTranfer));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //InterZone Excel Upload Using FileType Code Of Respective Zone
        public async Task<IActionResult> InterZonalPromotionUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.InterZonalPromotion);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.InterZonalPromotion));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //InterRegionTransfer Excel Upload Using FileType Code Of Respective Region
        public async Task<IActionResult> InterRegionRequestTransferUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.InterRegionRequestTransfer);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.InterRegionRequestTransfer));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //InterRegionPromotion Excel Upload Using FileType Code Of Respective Region
        public async Task<IActionResult> InterRegionalPromotionUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.InterRegionPromotion);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.InterRegionPromotion));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpGet]
        //Vacancy Pool Excel Upload Using FileType Code
        public async Task<IActionResult> VacancyPoolUpload()
        {
            HttpContext.Session.SetString("ExcelUploadFiletype", ExcelFileUploadName.VacancyPool);
            HttpContext.Session.SetInt32("ExcelFileTypeCode", Convert.ToInt32(ExcelFileType.VacancyPool));
            ViewBag.ExcelUploadFiletype = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            return View("ExcelUploadView");
        }

        [HttpPost]
        //Upload Excel
        public async Task<IActionResult> ExcelUpload(ExcelUploadViewModel model)
        {
            string uploadedBy = HttpContext.Session.GetString("Username");
            ExcelUploadResponseModel responseModel = await _service.UploadExcel(model, uploadedBy);
            var excelType = HttpContext.Session.GetString("ExcelUploadFiletype");
            ViewBag.ExcelUploadFiletype = excelType;
            ViewBag.ExcelFileTypeCode = HttpContext.Session.GetInt32("ExcelFileTypeCode");
            ViewBag.ExcelUploadResponse = responseModel == null ? null : responseModel;
            if(responseModel.Data.UploadStatus.ToLower() == "success")
            {
                string path = Path.Combine(this._environment.WebRootPath, "UploadedFiles", excelType, DateTime.Now.ToShortDateString().Replace("/", ""));
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                IFormFile postedFiles = model.ExcelFile;
                string fileName = Path.GetFileName(postedFiles.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFiles.CopyTo(stream);
                }
            }
           
            return View("ExcelUploadView");
        }

        [HttpPost]
        //Show The Upload History By Using Respective Upload Id 
        public async Task<IActionResult> ShowUploadHistory(int id)
        {
            var historyList = await _service.GetUploadHistories(id);
            return Json(historyList.Data);
        }

        [HttpPost]
        //Show All History Uploaded Data By Using Batch Id
        public async Task<IActionResult> GetUploadedDataByBatchId(int id, [FromBody] Pagination pagination)
        {
            int fileTypeCode = Convert.ToInt32(HttpContext.Session.GetInt32("ExcelFileTypeCode"));
            HttpContext.Session.SetInt32("batchId", id);
            var response = new Object();
            
            switch (fileTypeCode)
            {
                case (int)ExcelFileType.BranchMaster:
                    response = await _service.BranchMasterRecords(id, pagination);
                    return Json(response);

                case (int)ExcelFileType.DepartmentMaster:
                    response = await _service.DepartmentMasterRecords(id, pagination);
                    return Json(response);

                case (int)ExcelFileType.EmployeeMaster:
                    response = await _service.EmployeeMasterRecords(id, pagination);
                    return Json(response);

                case (int)ExcelFileType.InterRegionPromotion:
                    response = await _service.InterRegionPromotionRecords(id, pagination);

WebApplication1/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using PostingManagement.UI.CustomActionFilters;
using PostingManagement.UI.Models;
using PostingManagement.UI.Services.RoleService;

namespace PostingManagement.UI.Controllers
{
    [LoginFilter]
    public class RoleController : Controller
    {
        private readonly IRoleService roleService;
        readonly HttpClientHandler _clientHandler = new HttpClientHandler();
        public RoleController(IRoleService roleService, HttpClientHandler clientHandler)
        {
            this.roleService = roleService;
            _clientHandler = clientHandler;
        }

        [Route("Role/GetAllRoles")]
        [HttpGet]
        //Gets All Role 
        public async Task<IActionResult> GetAllRoles()
        {
            var responseList = await roleService.GetAllRoles();
            return Json(responseList);
        }

        [Route("Role/Addrole")]
        [HttpGet] 
        public async Task<IActionResult> Addrole()
        {
            if (TempData.ContainsKey("addRoleResponse"))
            {
                //Get the Dynamic ViewBag Using Response As True Or Flase.
                ViewBag.AddRoleResponse = TempData["addRoleResponse"].ToString();
            }
            return View();
        }

        [HttpPost]
        //Adding New Role.
        public async Task<IActionResult> Addrole(RoleModel roleModel)
        {
            var response = await roleService.AddRole(roleModel);
            //storing the response to tempData for showing status message in view
            if (response.Data != null)
            {
                TempData["addRoleResponse"] = response.Data == true ? "true" : "false";
            }
            else
            {
                TempData["addRoleResponse"] = "false";

            }
            return RedirectToAction("Addrole");

        }

        [HttpGet]
        //Delete Role.
        public async Task<IActionResult> RemoveRole(string id)
        {
            var response = await roleService.RemoveRole(id);
            return Json(response);
        }

        [HttpGet]
        //Get Role Id For Edit Role.
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleService.GetRoleById(id);
            return View(role.Data);
        }

        [HttpPost]
        //Edit Role By Using RoleId
        public async Task<IActionResult> EditRole(RoleModel roleModel)
        {
            var role = await roleService.EditRole(roleModel);
            return RedirectToAction("Addrole");
        }

        [HttpGet]
        //Check the Role Is Already Exist or Not.
        public async Task<IActionResult> IsRoleAlreadyExist(string roleName)
        {
            var response = await roleService.IsRoleAlreadyExist(roleName);
            return Json(response.Data);
        }
    }
}

WebApplication1/Views/Shared/MainView.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="" name="description">
    <meta content="" name="keywords">

    <title>@ViewData["Title"] - UI.PostingManagement</title>

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="/vendor/bootstrap/css/bootstrap.min.css?v=11010" rel="stylesheet">
    <link href="/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/datatables-1.13.1.css" rel="stylesheet" />

    <!-- Vendor CSS Files -->
    @*<link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">*@

    <!-- Template JS Files -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.datatables-1.13.1.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-between">
            <a asp-action="ShowDashboard" asp-controller="Dashboard" class="logo d-flex align-items-center">
                <img src="~/img/logo.png" alt="" />
                <span class="d-none d-lg-block">NS-Posting Management</span>

            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <li class="nav-item dropdown pe-3">
                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <img src="/img/profile-img.jpg" alt="Profile" class="rounded-circle">
                        <span class="d-none d-md-block ps-2">@Context.Session.GetString("Username")</span>
                    </a><!-- End Profile Iamge Icon -->
                </li>
                <li class="nav-item dropdown pe-3">
                    <a class="btn btn-danger" id="logout">
                        <span> Log-Out </span>
                    </a>
                </li>
            </ul>
        </nav>
    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link " asp-action="ShowDashboard" asp-controller="Dashboard">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#excelupload-nav" data-bs-toggle="collapse">
                    <i class="bi bi-file-earmark-arrow-up"></i><span>Excel Upload</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="excelupload-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">

                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="BranchMasterUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Branch Master</span>
                        </a>
                    </li><!-- End Branch Page Nav -->

                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="EmployeeMasterUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Employee Master</span>
                        </a>
                    </li><!-- End Inter Zonal Page Nav -->

                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="InterRegionalPromotionUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Inter Regional Promotion</span>
                        </a>
                    </li><!-- End InterRegion Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="InterRegionRequestTransferUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Inter Region Request Transfer</span>
                        </a>
                    </li><!-- End Promotion Preferrences Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="InterZonalPromotionUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Inter Zonal Promotion</span>
                        </a>
                    </li><!-- End Promotion List Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="InterZonalRequestTransferUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Inter Zonal Request Transfer</span>
                        </a>
                    </li><!-- End APAR Score Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="RegionMasterUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Region Master</span>
                        </a>
                    </li><!-- End Promotion List Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="ZoneMasterUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Zone Master</span>
                        </a>
                    </li><!-- End Register Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="DepartmentMasterUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Upload Department Master</span>
                        </a>
                    </li><!-- End Department Master Page Nav -->
                    <li class="nav-item">
                        <a class="nav-link collapsed" asp-action="VacancyPoolUpload" asp-controller="Posting">
                            <i class="bi bi-circle"></i>
                            <span>Vacancy Pool</span>
                        </a>
                    </li><!-- End Vacancy Pool Page Nav -->
                </ul>
            </li>
            @{
                if (Context.Session.GetString("UserRole")?.ToLower() == "admin")
                {
                    <li class="nav-item">
                        <a class="nav-link " asp-action="CreateUserName" asp-controller="AccountView">
                            <i class="bi bi-plus-square-dotted"></i>
                            <span>Create New User</span>
                        </a>
                    </li> <!--End Create User Name -->
                    <li class="nav-item">
                        <a class="nav-link " asp-action="AddRole" asp-controller="Role">
                            <i class="bi bi-plus-square-dotted"></i>
                            <span>Create New Role</span> <!--End Add Role -->
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="AddJobFamily" asp-controller="JobFamily">
                            <i class="bi bi-plus-square-dotted"></i>
                            <span>Create Job Family</span> <!--End Add Role -->
                        </a>
                    </li>

                }
            }
            <li class="nav-item">
                <a class="nav-link " asp-action="EmployeeTransferView" asp-controller="Transfer">
                    <i class="bi bi-plus-square-dotted"></i>
                    <span>Generate Employee Transfer</span> <!--End Add Role -->
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link " asp-action="ShowTriggerTable" asp-controller="TriggerView">
                    <i class="bi bi-plus-square-dotted"></i>
                    <span>Manage Triggers</span> <!--End Add Role -->
                </a>
            </li>
        </ul>
    </aside><!-- End Sidebar-->
    <main id="main" class="main">
        <div class="pagetitle">

            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

        </div><!-- End Page Title -->

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <script src="~/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script>
        $("#logout").click(function () {
            Swal.fire({
                title: 'Are you sure you want to Log-out?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes!'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = '@Url.Content("~/Login/Logout")';
                }
            });
        });
    </script>
</body>

</html>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/notify/0.4.2/notify.min.js"></script>

</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>