WebApplication1/Controllers/JobFamilyController.cs
using Microsoft.AspNetCore.Mvc;
using PostingManagement.UI.CustomActionFilters;
using PostingManagement.UI.Models;
using PostingManagement.UI.Services.JobFamilyServices;
namespace PostingManagement.UI.Controllers
{
    [LoginFilter]
    public class JobFamilyController : Controller
    {
        private readonly IJobFamilyService _jobFamilyService;
        readonly HttpClientHandler _clientHandler = new HttpClientHandler();
        public JobFamilyController(IJobFamilyService jobFamilyService,HttpClientHandler clientHandler)
        {
            _jobFamilyService = jobFamilyService;
            _clientHandler = clientHandler; 
        }

        //[Route("JobFamily/GetAllJobFamily")]
        [HttpGet]
        public async Task<IActionResult> GetAllJobFamily()
        {
            var jobFamilyList = await _jobFamilyService.GetAllJobFamily();
            return Json(jobFamilyList);
        }

        //[Route("JobFamily/AddJobFamily")]
        [HttpGet]
        public async Task<IActionResult> AddJobFamily()
        {
            if (TempData.ContainsKey("addJobFamilyResponse"))
            {
                ViewBag.AddJobFamilyResponse = TempData["addJobFamilyResponse"].ToString();
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddJobFamily(JobFamilyModel jobFamilyModel)
        {
            var response = await _jobFamilyService.AddJobFamily(jobFamilyModel);
            if (response.Data != null)
            {
                TempData["addJobFamilyResponse"] = response.Data == true ? "true" : "false";
            }
            else
            {
                TempData["addJobFamilyResponse"] = "false";

            }
            return RedirectToAction("AddJobFamily");

        }

        [HttpGet]
        public async Task<IActionResult> RemoveJobFamily(string id)
        {
            var response = await _jobFamilyService.RemoveJobFamily(id);
            return Json(response);
        }
        [HttpGet]
        public async Task<IActionResult> EditJobFamily(string id)
        {
            var jobFamily = await _jobFamilyService.GetJobFamilyById(id);
            return View(jobFamily.Data);  
        }
        [HttpPost]
        public async Task<IActionResult> EditJobFamily(JobFamilyModel jobFamilyModel)
        {
            var jobFamily = await _jobFamilyService.EditJobFamily(jobFamilyModel);
            return RedirectToAction("AddJobFamily");
        }
        [HttpGet]
        public async Task<IActionResult> IsJobFamilyAlreadyExist(string jobFamilyName)
        {
            var response = await _jobFamilyService.IsJobFamilyAlreadyExist(jobFamilyName);
            return Json(response.Data); 
        }
    }
}

WebApplication1/Views/JobFamily/AddJobFamily.cshtml
@model PostingManagement.UI.Models.JobFamilyModel

@{
    ViewData["Title"] = "AddJobFamily";
    Layout = "~/Views/Shared/MainView.cshtml";

}

<h1>Add Job Family</h1>
<hr />
<input type="hidden" value=@ViewBag.AddJobFamilyResponse id="addjobFamilyResponse" />
<script src="~/js/AddJobFamily.js"></script>
<div class="col-xxl-4 col-xl-12">

    <div class="card info-card customers-card">

        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="AddJobFamily" id="addJobFamilyForm">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div style="display:inline-flex;" class="w-100">
                            <div class="form-group my-3">
                                <label class="control-label">Job Family Name<i class="text-danger">*</i> </label>
                                <input asp-for="JobFamilyName" class="form-control" id="JobFamilyName" />
                            </div>
                            <div class="form-group m-3 d-flex align-items-end">
                                <input type="button" value="Save" id="addJobFamilyId" class="btn btn-success" />

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-xxl-4 col-xl-12">

    <div class="card info-card customers-card">

        <div class="card-body">
            <div id="assign">
                <partial name="GetAllJobFamily">
            </div>
        </div>
    </div>
</div>
<script>
    //Swal Alert For Confirmation Of Delete Role
    function Delete(id) {
        Swal.fire({
            title: 'Are you sure you want to Delete Job family?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = '/JobFamily/RemoveJobFamily?id=' + id;
            }
        });
    }
</script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

WebApplication1/Views/JobFamily/EditJobFamily.cshtml
@model PostingManagement.UI.Models.JobFamilyModel

@{
    ViewData["Title"] = "EditJobFamily";
    Layout = "~/Views/Shared/MainView.cshtml";
}

<h1>Edit Job Family</h1>

<hr />
<script src="~/js/EditJobFamily.js"></script>
<div class="col-xxl-4 col-xl-12">

    <div class="card info-card customers-card">

        <div class="card-body">
            <div class="row">
                <div class="col w-100">
                    <form asp-action="EditJobFamily">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div style="display:inline-flex;" class="w-100">
                            <input asp-for="JobFamilyId" class="form-control" type="hidden" />
                            <div class="form-group m-3">
                                <label class=" control-label">JobFamily Name<i class="text-danger">*</i> </label>
                                <input asp-for="JobFamilyName" class="form-control" />
                                <span asp-validation-for="JobFamilyName" class="text-danger"></span>
                            </div>
                            <div class="form-group m-3 d-flex align-items-end ">
                                <input type="submit" value="Save" class="btn btn-success m-4" />
                            </div>
                            <div class="form-group my-3 d-flex align-items-end ">
                                <a class="btn btn-primary my-4" asp-action="AddJobFamily" asp-controller="JobFamily">Back</a>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-xxl-4 col-xl-12">

    <div class="card info-card customers-card">

        <div class="card-body">
            <div id="assign">
                <partial name="GetAllJobFamily" />
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

WebApplication1/Views/JobFamily/GetAllJobFamily.cshtml
<table id="getAllJobFamilyId" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Job Family Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>